---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-east-2

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: argocd-server
      namespace: default
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AWSDenyAll"

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 1
