apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amazon-cloudwatch
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: amazon-cloudwatch
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/amazon-cloudwatch
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true
