apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demo
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/podinfo
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    helm:
      parameters:
      - name: "ingress.annotations.kubernetes\\.io/ingress.class"
        value: "alb"
      - name: "ingress.annotations.alb\\.ingress\\.kubernetes\\.io/scheme"
        value: "internet-facing"
      - name: "ingress.enabled"
        value: true
      - name: "service.type"
        value: "NodePort"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true
