#!/usr/bin/env bash
#
# Bootstraps Flux and Helm operator on a Kubernetes cluster.

set -e

GIT_ROOT_DIR="$(git rev-parse --show-toplevel)"

# Deploy Argo CD to the cluster.
kubectl create --dry-run -o yaml ns argocd | kubectl apply -f -
kubectl apply -n argocd -f "${GIT_ROOT_DIR}/base/argo-cd"

# Wait for Argo CD to start.
kubectl -n argocd rollout status deployment/argocd-server

# Expose Argo CD API Server.
kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
hostname="$(kubectl get svc -n argocd argocd-server -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')"

# Login using the CLI.
password="$(kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o name | cut -d'/' -f 2)"
argocd login "${hostname}" --insecure --username admin --password "${password}"

# Add credentials for the private repository.
personal_access_token="$(cat ${HOME}/personal_access_token)"
argocd repo add https://github.com/ecrews/gitops-demo-argocd --username ecrews --password "${personal_access_token}"

# Create and sync parent app.
argocd app create apps \
    --dest-namespace argocd \
    --dest-server https://kubernetes.default.svc \
    --repo https://github.com/ecrews/gitops-demo-argocd.git \
    --path charts/apps

argocd app sync apps
